// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HPvX0qNTj8PZhTINxmitaC75RQ2PsW8',
    appId: '1:943437475852:web:62dbd967dea4d5b8f1fe29',
    messagingSenderId: '943437475852',
    projectId: 'miner-enterprises',
    authDomain: 'miner-enterprises.firebaseapp.com',
    storageBucket: 'miner-enterprises.firebasestorage.app',
    measurementId: 'G-RY7E1T9ZW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZVA_3P3gHLZ7JS-_8o051KQVQ3dIYK4',
    appId: '1:943437475852:android:b5f4c051905b1d3af1fe29',
    messagingSenderId: '943437475852',
    projectId: 'miner-enterprises',
    storageBucket: 'miner-enterprises.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4h8N8sO8d3OywEr-hPw7-ZEZZMzo_sZY',
    appId: '1:943437475852:ios:18a2cc0cdac15fa3f1fe29',
    messagingSenderId: '943437475852',
    projectId: 'miner-enterprises',
    storageBucket: 'miner-enterprises.firebasestorage.app',
    iosBundleId: 'com.example.minerEnterprises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4h8N8sO8d3OywEr-hPw7-ZEZZMzo_sZY',
    appId: '1:943437475852:ios:18a2cc0cdac15fa3f1fe29',
    messagingSenderId: '943437475852',
    projectId: 'miner-enterprises',
    storageBucket: 'miner-enterprises.firebasestorage.app',
    iosBundleId: 'com.example.minerEnterprises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-HPvX0qNTj8PZhTINxmitaC75RQ2PsW8',
    appId: '1:943437475852:web:28fb6062ffd73a73f1fe29',
    messagingSenderId: '943437475852',
    projectId: 'miner-enterprises',
    authDomain: 'miner-enterprises.firebaseapp.com',
    storageBucket: 'miner-enterprises.firebasestorage.app',
    measurementId: 'G-W01E9T2L57',
  );

}